(package "lsp-uniteai"
         "0.1.0"
         "LSP Clients for UniteAI")

(website-url "https://github.com/emacs-openai/lsp-uniteai")
(keywords "convenience" "ai")

(package-file "lsp-uniteai.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)
(source 'melpa)

(depends-on "emacs" "27.1")
(depends-on "lsp-mode")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
